-- Xóa bảng nếu đã tồn tại để tránh lỗi
DROP TABLE IF EXISTS purchase_items;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS invoice_items;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS inventory_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS staff_logs;
DROP TABLE IF EXISTS users;

-- 1. Table users
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, 
  role TEXT NOT NULL CHECK (role IN ('admin', 'staff')),
  pin TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table staff_logs
CREATE TABLE staff_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  login_time TEXT NOT NULL,
  logout_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table products
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL,
  import_price NUMERIC NOT NULL DEFAULT 0,
  sell_price NUMERIC NOT NULL DEFAULT 0,
  initial_stock INTEGER NOT NULL DEFAULT 0,
  total_in INTEGER NOT NULL DEFAULT 0,
  total_out INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Table invoices
CREATE TABLE invoices (
  id TEXT PRIMARY KEY,
  time TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  employee_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL DEFAULT 'Khách lẻ',
  customer_phone TEXT,
  method TEXT NOT NULL,
  other_costs NUMERIC NOT NULL DEFAULT 0,
  total NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'completed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Table invoice_items
CREATE TABLE invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id TEXT REFERENCES invoices(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  price NUMERIC NOT NULL,
  qty INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Table purchases
CREATE TABLE purchases (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  supplier TEXT NOT NULL,
  note TEXT,
  total NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Table purchase_items
CREATE TABLE purchase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id TEXT REFERENCES purchases(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  qty INTEGER NOT NULL,
  cost NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- BẬT RLS (Row Level Security) CHO PHÉP MỌI NGƯỜI ĐỌC/GHI (DO ỨNG DỤNG LOCAL)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all on users" ON users FOR ALL USING (true);
CREATE POLICY "Allow public all on staff_logs" ON staff_logs FOR ALL USING (true);
CREATE POLICY "Allow public all on products" ON products FOR ALL USING (true);
CREATE POLICY "Allow public all on invoices" ON invoices FOR ALL USING (true);
CREATE POLICY "Allow public all on invoice_items" ON invoice_items FOR ALL USING (true);
CREATE POLICY "Allow public all on purchases" ON purchases FOR ALL USING (true);
CREATE POLICY "Allow public all on purchase_items" ON purchase_items FOR ALL USING (true);
CREATE POLICY "Allow public all on inventory_history" ON inventory_history FOR ALL USING (true);

-- INSERT MOCK DATA (Thay thế dữ liệu cứng trong PosContext)
INSERT INTO users (id, name, role, pin) VALUES 
  (1, 'Lê Hoa', 'admin', '1234'),
  (2, 'Trần Minh', 'staff', '0000');
  
-- Chúng ta cần reset sequence id để không bị trùng sau khi chèn id cứng (nếu id lớn hơn 2)
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

INSERT INTO products (id, name, category, unit, import_price, sell_price, initial_stock, total_in, total_out) VALUES 
  (1, 'Paracetamol 500mg', 'Thuốc', 'Hộp', 15000, 25000, 50, 200, 0),
  (2, 'Amoxicillin 500mg', 'Thuốc', 'Hộp', 45000, 75000, 30, 100, 0),
  (3, 'Vitamin C 1000mg', 'Thực phẩm bổ sung', 'Hộp', 35000, 55000, 40, 150, 0),
  (4, 'Bông Y Tế 500g', 'Vật tư y tế', 'Túi', 22000, 35000, 25, 60, 0);

SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- 8. Table inventory_history
CREATE TABLE inventory_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  month_year TEXT NOT NULL,
  initial_stock INTEGER NOT NULL DEFAULT 0,
  total_in INTEGER NOT NULL DEFAULT 0,
  total_out INTEGER NOT NULL DEFAULT 0,
  ending_stock INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_product_month UNIQUE (product_id, month_year)
);
