-- Migration: Add suppliers, bank accounts, and payment orders

CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE,
  name TEXT NOT NULL,
  bank_name TEXT,
  account_number TEXT,
  account_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Update purchases table
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS debt_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS payment_requested_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP WITH TIME ZONE;

-- We don't drop the old `supplier` TEXT column to keep old data working.

CREATE TABLE IF NOT EXISTS payment_orders (
  id TEXT PRIMARY KEY,
  purchase_id TEXT REFERENCES purchases(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_order_id TEXT REFERENCES payment_orders(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  transaction_ref TEXT,
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'SUCCESS'
);

-- RLS
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public all on suppliers" ON suppliers;
CREATE POLICY "Allow public all on suppliers" ON suppliers FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public all on payment_orders" ON payment_orders;
CREATE POLICY "Allow public all on payment_orders" ON payment_orders FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public all on payment_transactions" ON payment_transactions;
CREATE POLICY "Allow public all on payment_transactions" ON payment_transactions FOR ALL USING (true);
